# -*- coding: utf-8 -*-
"""
step3_extract_story_elements.py
Extract background, object, and emotion lists from the scene 1 story generated by step2.
"""
import json
import os
import re
import sys
from pathlib import Path

import anthropic
from dotenv import load_dotenv

load_dotenv()

MODEL_EXTRACT = "claude-haiku-4-5-20251001"


def extract_story_elements(client: anthropic.Anthropic, story_text: str) -> dict:
    """Extract background, object, and emotion lists from a generated story."""
    prompt = f"""아래 글에서 배경, 오브제, 감정 요소를 추출해라.

[글]
{story_text}

[정의]
- 배경: 공간, 장소, 지역, 시간대, 분위기적 환경
- 오브제: 글 안에 등장하는 구체적인 사물, 물건, 자연물, 신체 일부, 소품, 시각적 요소
- 감정: 글에서 느껴지는 정서, 심리 상태, 분위기

[출력 형식 - JSON만 출력, 다른 텍스트 없이]
{{
  "배경": ["항목1", "항목2"],
  "오브제": ["항목1", "항목2"],
  "감정": ["항목1", "항목2"]
}}"""

    message = client.messages.create(
        model=MODEL_EXTRACT,
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )
    raw = next((b.text for b in message.content if hasattr(b, "text")), "").strip()

    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if not match:
        raise ValueError(f"JSON 파싱 실패:\n{raw}")

    elements = json.loads(match.group())
    return {
        "배경": elements.get("배경", []),
        "오브제": elements.get("오브제", []),
        "감정": elements.get("감정", []),
    }


def main(input_path: str = "team2/output/scene1_story.txt", output_dir: str = "team2/output"):
    story_text = Path(input_path).read_text(encoding="utf-8")
    client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))

    print("[추출] 씬 1 스토리에서 배경/오브제/감정 요소 추출 중...")
    elements = extract_story_elements(client, story_text)

    for key in ("배경", "오브제", "감정"):
        elements[key] = list(dict.fromkeys(elements[key]))
        print(f"  {key} 후보 {len(elements[key])}개: {elements[key]}")

    out = Path(output_dir)
    out.mkdir(exist_ok=True)
    out_path = out / "scene1_story_elements.json"
    out_path.write_text(json.dumps(elements, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"\n요소 추출 저장 완료 -> {out_path}")
    return elements


if __name__ == "__main__":
    inp = sys.argv[1] if len(sys.argv) > 1 else "team2/output/scene1_story.txt"
    out = sys.argv[2] if len(sys.argv) > 2 else "team2/output"
    main(inp, out)
